<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ExpenseCount</name>
   <tag></tag>
   <elementGuidId>b1e9a085-e92e-4e9f-93e6-ccca62e14486</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#expenseCount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='expenseCount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00ab8027-20cd-4061-bcaf-7d71a9d88f1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control angular-input ng-untouched ng-pristine</value>
      <webElementGuid>2264d7ef-922f-4c19-9f32-af9401652990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e4dfce4d-7ff3-4b80-acb3-49d53bb05cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>34a76e09-feb0-4296-a56e-341ac8657603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>expenseCount</value>
      <webElementGuid>47244652-b3e3-4372-9299-1ccd533bd26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;expenseCount&quot;)</value>
      <webElementGuid>6b550b80-01fc-4cb7-8e20-ed49b0b0f8c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='expenseCount']</value>
      <webElementGuid>6ea0f02a-5bca-4d52-84dd-4f69aa35c3f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div/formly-form/formly-field[13]/ng-component/div/div/formly-field-text/div/input</value>
      <webElementGuid>7566e1e8-f59b-466a-afc7-80e7c1bf3ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//formly-field[13]/ng-component/div/div/formly-field-text/div/input</value>
      <webElementGuid>1f6e5b3a-3100-4f0f-8794-bb7123a0e4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'expenseCount']</value>
      <webElementGuid>42a364c5-f7be-42f4-82f4-e3beba2766d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
