<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_StartDate</name>
   <tag></tag>
   <elementGuidId>8ea44266-fea9-4e63-a601-4f0a3e99b449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fromDate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fromDate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a752231-9fce-442a-9f59-e60381bf6c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dp</value>
      <webElementGuid>994facda-694b-4b17-869c-105dd2587422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>container</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>17321813-ca6f-4cf7-803e-8e6ed9efcf33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control angular-calendar angular-input ng-touched ng-dirty ng-valid</value>
      <webElementGuid>cca1a56b-8a00-4c0e-bdca-83a86163d741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fromDate</value>
      <webElementGuid>3b0fec9f-79e4-42e3-9033-4cf980fed26d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>46a2a273-7381-4835-b79e-4ea210ee44b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fromDate&quot;)</value>
      <webElementGuid>8f6734bf-438e-4d3d-98fc-da57cbaf5b52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fromDate']</value>
      <webElementGuid>3293d1b6-1bf4-4909-a92e-23b545e65072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div/formly-form/formly-field/formly-group/formly-field/formly-date-picker/div/input</value>
      <webElementGuid>1f2bce70-3245-484c-b23d-29049a6e223f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//formly-date-picker/div/input</value>
      <webElementGuid>03d47ab4-25af-4901-b064-421fa713bb64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'dp' and @id = 'fromDate']</value>
      <webElementGuid>a66fdd1b-0678-47f2-b991-5ee966837214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
