<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TimesheetCount</name>
   <tag></tag>
   <elementGuidId>03db7be7-725d-43aa-bb4e-bf65490180a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#timesheetCount</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='timesheetCount']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8db00252-850d-4961-809a-c5748116116c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control angular-input ng-untouched ng-pristine</value>
      <webElementGuid>4ff7ea32-f357-4614-8bcb-961c6c02a0b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de9fdaee-ec04-48e3-b9a0-5dd066b45f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>disabled</name>
      <type>Main</type>
      <value>disabled</value>
      <webElementGuid>0b543509-2dc4-42d8-b03c-83084cb855e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timesheetCount</value>
      <webElementGuid>3be6c1ea-1ba1-4055-8570-0eabed4bea9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timesheetCount&quot;)</value>
      <webElementGuid>1198f232-0e5e-4251-9a14-495df4883a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='timesheetCount']</value>
      <webElementGuid>5b9aa699-c59c-462d-a3b4-d01af5790d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div/formly-form/formly-field[11]/ng-component/div/div/formly-field-text/div/input</value>
      <webElementGuid>7489b9cb-e679-4bb3-b1c5-9364c3580372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//formly-field[11]/ng-component/div/div/formly-field-text/div/input</value>
      <webElementGuid>357def73-f07c-47e5-b1f3-d3a40ed36941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'timesheetCount']</value>
      <webElementGuid>e2eb6c8e-4e8b-4839-9cbb-01b8ff3a1755</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
