<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ganttSubItem</name>
   <tag></tag>
   <elementGuidId>65de9f72-3cf5-45b5-8363-11c0a2aabfe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='Tasks']/tbody/tr[3]/td[2]/div/div/div/div[3]/table/tbody/tr[3]/td/div/table/tbody/tr[3]/td/div/table/tbody/tr[7]/td/div/table/tbody/tr[2]/td[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//table[@id='Tasks']/tbody/tr[3]/td[2]/div/div/div/div[3]/table/tbody/tr[3]/td/div/table/tbody/tr[${task}]/td/div/table/tbody/tr[${sub}]/td/div/table/tbody/tr[${row}]/td[${col}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> TSClassEdit TSCellBase TSType TSText TSCell TSNoLeft HideCol0Desc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testing Phase </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//table[@id='Tasks']/tbody/tr[3]/td[2]/div/div/div/div[3]/table/tbody/tr[3]/td/div/table/tbody/tr[${task}]/td/div/table/tbody/tr[${sub}]/td/div/table/tbody/tr[${row}]/td[${col}]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='Tasks']/tbody/tr[3]/td[2]/div/div/div/div[3]/table/tbody/tr[3]/td/div/table/tbody/tr[3]/td/div/table/tbody/tr[7]/td/div/table/tbody/tr[2]/td[3]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[8]/following::td[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon, 14 May 2018'])[2]/following::td[10]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thu, 26 Apr 2018'])[5]/preceding::td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mon, 14 May 2018'])[3]/preceding::td[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/div[3]/table/tbody/tr[3]/td/div/table/tbody/tr[3]/td/div/table/tbody/tr[7]/td/div/table/tbody/tr[2]/td[3]</value>
   </webElementXpaths>
</WebElementEntity>
