<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>defaultTypeListDropDown</name>
   <tag></tag>
   <elementGuidId>25576515-2325-4a0b-9120-3fa38f48a490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectListEditor</value>
      </entry>
      <entry>
         <key>XPATH</key>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
