<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_localRate2</name>
   <tag></tag>
   <elementGuidId>fce168a8-5850-4247-ab57-f3019eae5c4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='localRate'])[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;departmentplanningratestable&quot;)/div[@class=&quot;visible&quot;]/datatable-body[@class=&quot;datatable-body&quot;]/datatable-selection[1]/datatable-scroller[@class=&quot;datatable-scroll&quot;]/datatable-row-wrapper[@class=&quot;datatable-row-wrapper&quot;]/datatable-body-row[@class=&quot;datatable-body-row datatable-row-odd&quot;]/div[@class=&quot;datatable-row-center datatable-row-group&quot;]/datatable-body-cell[@class=&quot;datatable-body-cell sort-active&quot;]/div[@class=&quot;datatable-body-cell-label&quot;]/formly-field[1]/formly-field-text[1]/div[@class=&quot;inputGroup&quot;]/input[@id=&quot;localRate&quot;][count(. | //*[@type = 'text' and @class = 'form-control angular-input ng-pristine ng-invalid ng-touched' and @id = 'localRate']) = count(//*[@type = 'text' and @class = 'form-control angular-input ng-pristine ng-invalid ng-touched' and @id = 'localRate'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>datatable-body-row.datatable-body-row.datatable-row-odd > div.datatable-row-center.datatable-row-group > datatable-body-cell.datatable-body-cell.sort-active > div.datatable-body-cell-label > formly-field > formly-field-text > div.inputGroup > #localRate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control angular-input ng-pristine ng-invalid ng-touched</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>localRate</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;departmentplanningratestable&quot;)/div[@class=&quot;visible&quot;]/datatable-body[@class=&quot;datatable-body&quot;]/datatable-selection[1]/datatable-scroller[@class=&quot;datatable-scroll&quot;]/datatable-row-wrapper[@class=&quot;datatable-row-wrapper&quot;]/datatable-body-row[@class=&quot;datatable-body-row datatable-row-odd&quot;]/div[@class=&quot;datatable-row-center datatable-row-group&quot;]/datatable-body-cell[@class=&quot;datatable-body-cell sort-active&quot;]/div[@class=&quot;datatable-body-cell-label&quot;]/formly-field[1]/formly-field-text[1]/div[@class=&quot;inputGroup&quot;]/input[@id=&quot;localRate&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='localRate'])[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ngx-datatable[@id='departmentplanningratestable']/div/datatable-body/datatable-selection/datatable-scroller/datatable-row-wrapper[2]/datatable-body-row/div[2]/datatable-body-cell[3]/div/formly-field/formly-field-text/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//datatable-row-wrapper[2]/datatable-body-row/div[2]/datatable-body-cell[3]/div/formly-field/formly-field-text/div/input</value>
   </webElementXpaths>
</WebElementEntity>
