<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tree_Level2</name>
   <tag></tag>
   <elementGuidId>f08f7728-c316-4821-b442-c9da5552bbee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${custProj}' or . = '${custProj}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MyTree']/table/tbody/tr/td/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cf3d8a4b-4535-480e-855a-daae457e6566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tree-folder-header</value>
      <webElementGuid>b04310d3-e55d-4ba5-8817-39c32b09fb24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${custProj}</value>
      <webElementGuid>c22c5468-1f5e-4ba4-b52b-48dd9fc8b83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MyTree&quot;)/table[1]/tbody[1]/tr[1]/td[1]/div[@class=&quot;tree-folder&quot;]/div[@class=&quot;tree-folder-content&quot;]/div[@class=&quot;tree-folder&quot;]/div[@class=&quot;tree-folder-header&quot;]</value>
      <webElementGuid>b9d0ba09-afd8-46d2-b1f4-9700c53a6553</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MyTree']/table/tbody/tr/td/div/div[2]/div/div</value>
      <webElementGuid>cd835c5b-c0d7-4c41-a8f1-012f923c9907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Company'])[1]/following::div[3]</value>
      <webElementGuid>ae75873c-798c-4ed7-8dc2-8bfa51eab8bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Innovation'])[2]/following::div[11]</value>
      <webElementGuid>ffab29ca-22fa-4643-84ef-f58194d1de1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PSA Solutions Inc'])[1]/preceding::div[3]</value>
      <webElementGuid>e2dfe496-de0b-4004-92b3-f033467fec70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/div/div</value>
      <webElementGuid>7658049d-8d68-4b83-89a6-84877b339d37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
