<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tree_Level3</name>
   <tag></tag>
   <elementGuidId>3a165ee6-4259-478d-a43a-a785cc17a519</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${company}' or . = '${company}')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MyTree']/table/tbody/tr/td/div/div[2]/div/div[2]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>46c128c6-8710-41c8-9a72-d4b7c3d6e740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tree-folder-header</value>
      <webElementGuid>7f68f893-922f-408a-9c48-fc3b33fd3aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${company}</value>
      <webElementGuid>d81f01d2-6d9e-468b-9385-6408ad1ab463</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MyTree&quot;)/table[1]/tbody[1]/tr[1]/td[1]/div[@class=&quot;tree-folder&quot;]/div[@class=&quot;tree-folder-content&quot;]/div[@class=&quot;tree-folder&quot;]/div[@class=&quot;tree-folder-content&quot;]/div[@class=&quot;tree-folder&quot;]/div[@class=&quot;tree-folder-header&quot;]</value>
      <webElementGuid>11c21396-8685-488f-8372-d71553393f82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MyTree']/table/tbody/tr/td/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>39ea3a1c-2082-4605-93ff-a69b9027cde6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Projects'])[1]/following::div[3]</value>
      <webElementGuid>f29ed10e-11b6-44b5-a383-4654f947b53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Company'])[1]/following::div[8]</value>
      <webElementGuid>3668471a-e63d-4e81-b98c-12a683ec88b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Project Innovation'])[3]/preceding::div[3]</value>
      <webElementGuid>63dad12f-c989-4799-9747-63831594f14d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/div/div[2]/div/div[2]/div/div</value>
      <webElementGuid>ac27a738-9bde-4ee1-b848-dc87ee089536</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
