<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>menu_Deliverables</name>
   <tag></tag>
   <elementGuidId>d74a14a4-c731-443d-9e80-78724745da16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'Deliverbles' and @href = '#' and @class = ' partial']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Deliverbles']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6aa12801-85a9-4862-b579-329d64862f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Deliverbles</value>
      <webElementGuid>9be37afa-beba-4224-8149-d394692ba8fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d613b107-617c-4261-858f-0e5dec9ee989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> partial</value>
      <webElementGuid>7a780ac1-30d7-4c6c-aef0-3aeb54ac651e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>MVC-PRL1-DELIVERABLES</value>
      <webElementGuid>be648b51-9717-41f7-9bd4-8a8835a44868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>navigator_GotoSingleView(this)</value>
      <webElementGuid>f77d71ef-f8ea-454e-bdfc-92cf6ec75a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-url</name>
      <type>Main</type>
      <value>/Frame/Index/MVC-PRL1-DELIVERABLES?Page=%2FKIPWebPortal%2Fdashboard%2Fcustom%2FProjectDashboard%2FDeliverableControl.aspx%3FProjectCode%3DPRJ008&amp;PageTitle=Tech%20Service%20Delivery&amp;FavouriteItem=KeyedIn.Projects.Web.Models.Favourites.Favourite&amp;ProjectCode=PRJ008&amp;ShowProjectToolbar=True&amp;SetBreadCrumb=True&amp;ShowPageTitle=True&amp;TitleIcon=%20fa%20fa-briefcase%20themeprimary%20&amp;Label=My%20Projects&amp;Type=SingleProject&amp;Buttons=KeyedIn.Projects.Model.Common.OperationButtons&amp;RefreshUrl=%2FDashboard%2FIndex%2FMVC-PRL1-OVERVIEW</value>
      <webElementGuid>404796b0-3bf7-4592-a8e5-f9d445ab9e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 Deliverables
                            </value>
      <webElementGuid>0fe034a1-9017-479c-ae55-f4af1c91f2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Deliverbles&quot;)</value>
      <webElementGuid>20f78644-1b6f-4d7e-9627-687485cc7162</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Deliverbles']</value>
      <webElementGuid>d0265741-3973-417d-ab25-7a5e0230178a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kipTabStrip']/div/ul/li[6]/a</value>
      <webElementGuid>20f878bf-af22-44a1-8e97-4f07c5aa1680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clone'])[1]/following::a[6]</value>
      <webElementGuid>8db58a88-33ef-4af6-a645-91a1a4a25e1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to favourites'])[1]/following::a[7]</value>
      <webElementGuid>0362f5fd-d8ea-4d1f-be62-d4bd72fa6517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Layouts'])[1]/preceding::a[8]</value>
      <webElementGuid>a3993697-aaf7-4308-be32-5fe04fbfb34d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[52]</value>
      <webElementGuid>34cc0978-cfa5-4a4c-80ff-38a2c54e0ae1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/ul/li[6]/a</value>
      <webElementGuid>f12f5e72-8679-47e2-9521-f422f5b55c46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
