<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>settings</name>
   <tag></tag>
   <elementGuidId>cf645e96-eec0-488b-9ea7-c3438b80b8bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;btn-settings&quot;)/i[@class=&quot;icon fa fa-cog&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btn-settings']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>95f95e32-538e-4a5a-bda1-b044d6f28d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon fa fa-cog</value>
      <webElementGuid>fc065d41-6447-41f0-a40c-c0281dcb0356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-settings&quot;)/i[@class=&quot;icon fa fa-cog&quot;]</value>
      <webElementGuid>30016192-9dac-4beb-b345-53b7da1cfeea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='btn-settings']/i</value>
      <webElementGuid>f77c11d8-dca8-4ba1-ad5c-9bbaf1ef9bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code Converter'])[1]/following::i[1]</value>
      <webElementGuid>f9ca8cd4-669f-47c1-913b-7fc4779572e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skills'])[2]/following::i[1]</value>
      <webElementGuid>50ecf01a-b297-456f-8ce9-066438739689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New'])[1]/preceding::i[2]</value>
      <webElementGuid>c95920a2-6d8c-4878-bc05-68637671c878</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assignment'])[1]/preceding::i[3]</value>
      <webElementGuid>e10aee1b-fd87-4071-8284-3e2f3c96112b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/i</value>
      <webElementGuid>d1a1659a-e7e6-48dc-ab6c-6aa1c1f50131</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
