<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Expenses</name>
   <tag></tag>
   <elementGuidId>f9c98988-49e1-449b-bd7c-650726f39e00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='widget-menu']/div[6]/div/h4/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '#widget-group-Expenses' and (text() = '
                                            Expenses
                                        ' or . = '
                                            Expenses
                                        ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d09a9d13-92bf-4e8f-ac09-7777df0638e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion-toggle collapsed</value>
      <webElementGuid>6e536d64-8f58-4ee6-bc1a-d4b6c46fedbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>collapse</value>
      <webElementGuid>0b682fbf-753a-405a-96ef-115c2c660033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-parent</name>
      <type>Main</type>
      <value>#widget-menu</value>
      <webElementGuid>ac4ab05a-37b0-473e-b815-6701f1d3068f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#widget-group-Expenses</value>
      <webElementGuid>e5bdabf7-3f80-4f26-97e5-f11123a792d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd665fab-d040-46d6-b5af-e7551c920e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                            Expenses
                                        </value>
      <webElementGuid>6d1a8b17-17a0-4869-a1df-2509be6ea54d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget-menu&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-heading&quot;]/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;accordion-toggle collapsed&quot;]</value>
      <webElementGuid>6412bbe5-abe5-4a50-bb8e-3a4f5f87067a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='widget-menu']/div[6]/div/h4/a</value>
      <webElementGuid>41239564-56a8-4f02-9e30-1e7f5c8385b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Expenses')]</value>
      <webElementGuid>f4665cc0-de1b-4aa5-a267-ed6246d24601</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Displays a filterable list of Deliverables that you are the owner of'])[1]/following::a[1]</value>
      <webElementGuid>b9c34cd3-0778-4eb8-8ed1-72d80347e90b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Deliverables'])[1]/following::a[1]</value>
      <webElementGuid>89e1edda-9d21-482d-8d15-f9bb235cbb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[10]/preceding::a[1]</value>
      <webElementGuid>9d61c091-f562-4cb9-89d1-050785fa1ba7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expenses'])[3]/preceding::a[1]</value>
      <webElementGuid>72f79ee1-1dec-4b8a-ac25-28d75c4c6b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#widget-group-Expenses')]</value>
      <webElementGuid>18e70866-926b-4af3-970a-409760325a44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/h4/a</value>
      <webElementGuid>922d31ff-1d20-4372-aa45-4e6cc4ce8d0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
