<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>actionViewsButton</name>
   <tag></tag>
   <elementGuidId>13f66cca-1723-44ea-bb2a-c22d4ac1ad50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id='widget-group-Action_Views']//div[@class='panel-body']//div[${button}]//div[1]//div[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@id='widget-group-Action_Views']//div[@class='panel-body']//div[${button}]//div[1]//div[1]</value>
   </webElementProperties>
</WebElementEntity>
