<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ProfileSettings</name>
   <tag></tag>
   <elementGuidId>025bb19a-89c0-4481-ba29-6b48e5ebe183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Code Converter'])[1]/following::a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.login-area.dropdown-toggle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9f8bb281-5dcb-493a-9eb2-f3a1e25bff65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login-area dropdown-toggle</value>
      <webElementGuid>fa137030-c592-4343-8b1c-b22f0a1c9795</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>3442b490-acd4-41b4-a0ec-4024437323fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;navbar&quot;]/div[@class=&quot;navbar-inner&quot;]/div[@class=&quot;navbar-container&quot;]/div[@class=&quot;navbar-header pull-right&quot;]/div[@class=&quot;navbar-account&quot;]/ul[@class=&quot;account-area favourites-menu&quot;]/li[7]/a[@class=&quot;login-area dropdown-toggle&quot;]</value>
      <webElementGuid>1f6cf6b8-39e2-4c04-95d7-49d35f09cdbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Code Converter'])[1]/following::a[2]</value>
      <webElementGuid>ac6917bf-e041-4d5d-8aee-c0c39a45a2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action Views'])[1]/following::a[3]</value>
      <webElementGuid>c620c50d-c064-4dfc-87f2-8db72ada55cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dave Lees'])[1]/preceding::a[1]</value>
      <webElementGuid>c6c77b57-8075-43da-8669-d7f20d563393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AUTOTEST@WORKFLOWS.COM'])[1]/preceding::a[1]</value>
      <webElementGuid>8122200d-dfa0-478e-98f3-ddc7e9c62ab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/a</value>
      <webElementGuid>6b1df2f2-5d22-429f-8b6f-3efbc667aa21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
