<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>addRowAtEnd</name>
   <tag></tag>
   <elementGuidId>ea168fb7-2665-442a-80ff-86e047cd34b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'ctl00_phFormContent_imgAddDemand' and @title = 'Add a row at the end' and @ref_element = 'Object Repository/KeyedInProjects/MyWorkDashboard/MyProjectsMenu/Forecasts/iframe']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_phFormContent_imgAddDemand']

ctl00_phFormContent_imgAddDemand</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2f2ff0cc-c412-481c-95d6-6788bd387a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/menuitem_addrow_colour.gif</value>
      <webElementGuid>4c620f71-5ba0-49b5-a99b-1400d45c36ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$phFormContent$imgAddDemand</value>
      <webElementGuid>a885353a-5049-4ebe-adab-637d27cdec39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>ea4a183e-8074-4f54-98aa-60f64e6c3e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_phFormContent_imgAddDemand</value>
      <webElementGuid>39272110-de7f-478f-b264-dcfd64e37b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Add a row at the end</value>
      <webElementGuid>44f476e2-5617-4fc2-8edc-9ab8fe841533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Add a row at the end</value>
      <webElementGuid>dc6748a3-b0b5-4f7b-abbc-ef95a35ea4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_phFormContent_imgAddDemand&quot;)</value>
      <webElementGuid>cb1b9ed6-323d-4577-aa0a-a579522aa383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/KeyedInProjects/MyWorkDashboard/MyProjectsMenu/Forecasts/iframe</value>
      <webElementGuid>ea627700-14c3-4e45-bcf9-fc5442dd55f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_phFormContent_imgAddDemand']</value>
      <webElementGuid>37841d0e-9ce1-4ba2-91ff-b3d444c79a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tblForm']/tbody/tr[4]/td/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td[11]/input</value>
      <webElementGuid>2e060404-176b-4c55-a1da-cecf1c5159e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/following::input[2]</value>
      <webElementGuid>31567999-a0cf-4b02-9355-0ff82ebb5408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/following::input[3]</value>
      <webElementGuid>44847933-08aa-4509-bafa-dd35adc01a92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Effort:'])[1]/preceding::input[11]</value>
      <webElementGuid>23176235-8e49-48ab-b27c-85bc51ed5c32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Historical:'])[1]/preceding::input[11]</value>
      <webElementGuid>b69d7718-698a-4a9f-a9ab-2e7f2bee5463</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/input</value>
      <webElementGuid>1ae094c8-00ec-4d09-83e2-f22e58f9fc4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
