<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_SaveCloseButton_Alt</name>
   <tag></tag>
   <elementGuidId>a897c6e6-2aeb-4837-8c06-2a787ff177aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-secondary.saveclosebutton.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Save and Close']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90a4473d-10e2-4ec6-b565-24cf8e3723c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>bedfde54-f0e6-4cff-a869-476407cbdb76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-secondary saveclosebutton ng-star-inserted</value>
      <webElementGuid>bea14d0b-8b38-4aa6-98d3-d2ac025efe3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Save and Close</value>
      <webElementGuid>889f9842-0141-424d-b286-85e01a26279c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-footer&quot;)/div[@class=&quot;savebuttongroup ng-star-inserted&quot;]/input[@class=&quot;btn btn-secondary saveclosebutton ng-star-inserted&quot;]</value>
      <webElementGuid>db2a21bc-53e4-4a47-a350-ec896e1044a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Save and Close']</value>
      <webElementGuid>a842a3aa-a99f-485b-9127-af4d73f693fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-footer']/div[2]/input</value>
      <webElementGuid>35c540c7-8b1a-4012-9f6b-5133e63b7306</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-modal-footer/div/div[2]/input</value>
      <webElementGuid>a2014dfd-9e45-42e9-9621-4084e1b70301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>d96fd588-561b-497f-afea-00e14a4d1d07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
