<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Description</name>
   <tag></tag>
   <elementGuidId>90fa7bd1-4972-4e9e-af8b-1d4fd1c1bc34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;ctl00_phFormContent_txtDescription_ucRadEditor_contentIframe&quot;)[count(. | //*[@id = 'ctl00_phFormContent_txtDescription_ucRadEditor_contentIframe' and @ref_element = 'Object Repository/KeyedInProjects/MyWorkDashboard/SearchMenu/ColumnChooser/iframe']) = count(//*[@id = 'ctl00_phFormContent_txtDescription_ucRadEditor_contentIframe' and @ref_element = 'Object Repository/KeyedInProjects/MyWorkDashboard/SearchMenu/ColumnChooser/iframe'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>javascript:'&lt;html>&lt;/html>';</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_phFormContent_txtDescription_ucRadEditor_contentIframe</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Rich text editor with ID ctl00_phFormContent_txtDetails_ucRadEditor</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Your browser does not support inline frames or is currently configured not to display inline frames.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_phFormContent_txtDescription_ucRadEditor_contentIframe&quot;)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/KeyedInProjects/MyWorkDashboard/SearchMenu/ColumnChooser/iframe</value>
   </webElementProperties>
</WebElementEntity>
