<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tableLength_pages</name>
   <tag></tag>
   <elementGuidId>6455ca42-ca86-46a3-b632-ebf06c507839</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='40e594eb-a65d-4315-8d8d-c7ccc8e8717b']/div[6]/div[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[contains(text(), 'Showing ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d1b90753-e343-4ef4-bf11-12deecbca94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-xs-5 text-align-left padding-top-10</value>
      <webElementGuid>054d235d-78f3-408f-b5b8-c4ffb48ac464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                    Showing 1 to 10 of 13 entries
                </value>
      <webElementGuid>d68fae29-016d-4337-aea7-8e4e0c5b18fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[contains(text(), 'Showing ')]</value>
      <webElementGuid>07fb9427-e640-43bd-9ceb-7a392d032f79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='40e594eb-a65d-4315-8d8d-c7ccc8e8717b']/div[6]/div[2]</value>
      <webElementGuid>27c88ffe-c9ac-46dd-98d4-cb281337cf16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[27]/following::div[3]</value>
      <webElementGuid>c8de53d8-4c1a-4f06-875a-cc53420e92af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[38]/following::div[3]</value>
      <webElementGuid>bc4d2bd9-44ea-4792-8cf2-91017e757483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/preceding::div[7]</value>
      <webElementGuid>ede82858-2868-4d96-a3db-8cc0247d5157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading'])[1]/preceding::div[7]</value>
      <webElementGuid>d80eadc1-0cac-4f7b-a0b9-530dfd9c4252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]</value>
      <webElementGuid>24397ef2-6c00-4401-8acd-ad44438e5b64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
