<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>to_BenefitHeaderDates</name>
   <tag></tag>
   <elementGuidId>4ce47ad4-4fd8-4a9a-aa61-ff2f8f0a9d45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//thead/tr[2]/td[${col}]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//thead/tr[2]/td[${col}]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/KeyedInProjects/MyWorkDashboard/SearchMenu/ColumnChooser/addExpenseTypeFrame</value>
   </webElementProperties>
</WebElementEntity>
