<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>costCentreGuidanceNotes_InTab</name>
   <tag></tag>
   <elementGuidId>c265a521-5aa3-444b-bca9-7bdae211cfa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-container']/div/formly-form/formly-field/formly-field-tabset/formly-tabs-tabset/div/formly-field[2]/formly-field-tab/formly-tabs-tab/formly-field/formly-label/label/i</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-toggle = 'tooltip' and contains(@class, 'fa fa-info-circle tooltip-info') and @data-original-title = '${tip}']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.angular-label.control-label > i.fa.fa-info-circle.tooltip-info</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>2ec9d74a-2bf9-40ca-a718-7b2fda6f5a29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>777e326d-0dd8-4736-b493-a2c3fe6c5ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>tooltip</value>
      <webElementGuid>9fc07b34-a51b-469a-8557-4c9d2173bfe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>valign</name>
      <type>Main</type>
      <value>middle</value>
      <webElementGuid>a2e6c7d5-d0eb-4c6e-a992-9cd83100328f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placement</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>8b9dacd6-4c66-4beb-9dcd-a8d81dbe5ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-info-circle tooltip-info</value>
      <webElementGuid>9029b62a-a69b-4330-9d0f-ce944170edd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-title</name>
      <type>Main</type>
      <value>${tip}</value>
      <webElementGuid>00a1f10e-6222-42dd-9f30-33f791f624b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>tooltip462861</value>
      <webElementGuid>8ec2b387-ed7e-40d5-8bca-d8c0226f2d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-1-1&quot;)/div[@class=&quot;mat-tab-body-content ng-tns-c284-1 ng-trigger ng-trigger-translateTab&quot;]/formly-field[@class=&quot;ng-star-inserted&quot;]/formly-field-tab[@class=&quot;ng-star-inserted&quot;]/formly-tabs-tab[1]/formly-field[@class=&quot;ng-star-inserted&quot;]/formly-label[@class=&quot;ng-star-inserted&quot;]/label[@class=&quot;angular-label control-label&quot;]/i[@class=&quot;fa fa-info-circle tooltip-info ng-star-inserted&quot;]</value>
      <webElementGuid>4316389f-22b3-4cef-98b7-61996d9c35d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div/formly-form/formly-field/formly-field-tabset/formly-tabs-tabset/div/formly-field[2]/formly-field-tab/formly-tabs-tab/formly-field/formly-label/label/i</value>
      <webElementGuid>ddeccaf8-bcf0-42d8-9b98-e205091f728e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//formly-label/label/i</value>
      <webElementGuid>725f1d7b-03d2-4063-b19b-1d26b9866f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
