<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FormattedTextField</name>
   <tag></tag>
   <elementGuidId>9ddb75f4-78d8-45eb-a918-9cfb537357dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-container']/div/formly-form/formly-field/formly-field-tabset/formly-tabs-tabset/div/formly-field[2]/formly-field-tab/formly-tabs-tab/formly-field[2]/ng-component/div/div/custom-field-free-text/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.note-editor.note-frame.panel.panel-default</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>note-editor note-frame panel panel-default</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Open Sans  Helvetica Arial Arial Black Comic Sans MS Courier New Times Garamond16 8 9 10 11 12 14 18 24 36  Background Color      Transparent          Foreground Color      Reset to default         pQuoteCodeHeader 1Header 2Header 3Header 4Header 5Header 6   1.0 1.2 1.4 1.5 1.6 1.8 2.0 3.0       1 x 1                            ×      Insert Link        Text to displayTo what URL should this link go? Open in new window    Insert Link              ×      Insert Image        Select from filesImage URL    Insert Image              ×      Insert Video        Video URL? (YouTube, Vimeo, Vine, Instagram, DailyMotion or Youku)    Insert Video              ×      Help        ENTERInsert ParagraphCTRL+ZUndoes the last commandCTRL+YRedoes the last commandTABTabSHIFT+TABUntabCTRL+BSet a bold styleCTRL+ISet a italic styleCTRL+USet a underline styleCTRL+SHIFT+SSet a strikethrough styleCTRL+BACKSLASHClean a styleCTRL+SHIFT+LSet left alignCTRL+SHIFT+ESet center alignCTRL+SHIFT+RSet right alignCTRL+SHIFT+JSet full alignCTRL+SHIFT+NUM7Toggle unordered listCTRL+SHIFT+NUM8Toggle ordered listCTRL+LEFTBRACKETOutdent on current paragraphCTRL+RIGHTBRACKETIndent on current paragraphCTRL+NUM0Change current block's format as a paragraph(P tag)CTRL+NUM1Change current block's format as H1CTRL+NUM2Change current block's format as H2CTRL+NUM3Change current block's format as H3CTRL+NUM4Change current block's format as H4CTRL+NUM5Change current block's format as H5CTRL+NUM6Change current block's format as H6CTRL+ENTERInsert horizontal ruleCTRL+KShow Link Dialog    Summernote 0.8.2 · Project · Issues  </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-container&quot;)/div[@class=&quot;notabs&quot;]/formly-form[1]/formly-field[1]/formly-field-tabset[1]/formly-tabs-tabset[1]/div[@class=&quot;content&quot;]/formly-field[2]/formly-field-tab[1]/formly-tabs-tab[1]/formly-field[2]/ng-component[1]/div[@class=&quot;form-group row&quot;]/div[1]/custom-field-free-text[1]/div[@class=&quot;note-editor note-frame panel panel-default&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-container']/div/formly-form/formly-field/formly-field-tabset/formly-tabs-tabset/div/formly-field[2]/formly-field-tab/formly-tabs-tab/formly-field[2]/ng-component/div/div/custom-field-free-text/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//custom-field-free-text/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
