<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_EntityPicker</name>
   <tag></tag>
   <elementGuidId>0c421ed2-3db4-44c3-9ef9-a22503d70bf4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ae479a5aa6ce-1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//ng-dropdown-panel[@class = 'ng-dropdown-panel angular-input ng-star-inserted ng-select-bottom' and (contains(text(), '${value}') or contains(., '${value}'))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ae479a5aa6ce-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ng-dropdown-panel</value>
      <webElementGuid>0bc76fef-c9d2-4496-a278-806588bf270c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-dropdown-panel angular-input ng-star-inserted ng-select-bottom</value>
      <webElementGuid>3dbfc68e-2579-4b79-a8a7-e1663e3978e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>28e4c533-dcaf-445a-a85e-45ede8197ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>97a6922c-c349-4a0f-b9f6-ed2cced4399c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ae479a5aa6ce-1</value>
      <webElementGuid>ec92a247-db80-400a-8df4-3cbebe3bb667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${value}</value>
      <webElementGuid>6399f35a-f4cb-4dc3-bf54-c8128367d0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ae479a5aa6ce-1&quot;)</value>
      <webElementGuid>aa503e2f-086b-44b8-be53-45e02d40af64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='ae479a5aa6ce-1']</value>
      <webElementGuid>9a760f2e-8a03-45bd-b05f-ccd98a3b3817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ng-dropdown-panel[@id='ae479a5aa6ce']/div/div[2]/div[2]</value>
      <webElementGuid>41886aa0-d8dc-4456-8c52-1f6bd8274ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[3]/following::div[7]</value>
      <webElementGuid>c980dbf9-b6fe-41c2-8220-73d85c8cf4ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[2]/following::div[15]</value>
      <webElementGuid>89dff61a-af3b-4537-b42e-88da1693445a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='pskuyhhjshqa'])[1]/preceding::div[1]</value>
      <webElementGuid>5fb97238-01c0-4466-b1cf-72ae3b97ebea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-dropdown-panel/div/div[2]/div[2]</value>
      <webElementGuid>f9eac1af-bbf6-4004-bfa0-f1e3f12a6d5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
